server:
  port: 8086
spring:
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8090
      http-method-specify: true # 开启请求方式前缀

hm:
  db:
    database: hm-pay
    port: 3306
    host: 127.192.40.136
    un: root
    pw: 123
  swagger:
    title: 黑马商城支付服务接口文档
    desc: 黑马商城支付服务接口文档
    package: com.hmall.pay.controller

feign:
  sentinel:
    enabled: true # 开启feign对sentinel的支持